### ISSUE TITLE
Two planets have the wrong names

### ISSUE THREAD

**Issue by Ymbirtt** [deadeyejoe/deck#1]
Using this map as an example: https://conclave.mistake-not.net/#WyJeICIsIn46diIsMSwifjp0IiwiMTggNzggMjkgNDYgMzggNDggNjUgMjMgNDcgNDIgMjEgNDkgNzMgMzAgMzkgNjQgMzcgMzYgNjcgMjQgNzAgNjEgUDIgMzEgMzQgUDMgMzUgNDQgUDQgNzcgNjYgNjAgUDUgODAgNzYgMjIgUDEiXQ==

System tile 61 at coordinates 2, 1, -3 is mislabelled as containing the planet "Perimeter" in the bottom right of the screen while hovering:

![image](https://github.com/deadeyejoe/deck/assets/1297752/9e54379a-1ec3-4eaa-827e-85cd6d4736ee)

Looking at the tile image, this planet should be called Ang. This is also the case for system tile 73, where Cealdri is misidentified as Lisis.

**Comment by Ymbirtt** [comment]
Thanks - incidentally, do you have some brief notes on how to run a local copy of this? I'm interested in adding another couple of bits and pieces if I find the time.

**Comment by deadeyejoe** [comment]
Sure I can write some up. Are you familiar with clojure or clojurescript at all? What would you be thinking of adding?

**Comment by Ymbirtt** [comment]
I'm afraid I'm totally new to the Clojue ecosystem, though snooping around your other repos I've found your Codenames project, which does seem to include some documentation. If that's relevant to Conclave, I can give that a shot?

Because of the number of friends I have, I usually play 5 player games, so was hoping to add in definitions for the 5-player notch and flat maps: 

![image](https://github.com/deadeyejoe/deck/assets/1297752/8b4b5ea7-1ee2-46c3-977a-c53d457c02f2)
![image](https://github.com/deadeyejoe/deck/assets/1297752/de632f2b-b21d-4758-982b-84978dd956c7)

Looking at your definitions in [data/layouts.cljc](https://github.com/deadeyejoe/deck/blob/master/projects/conclave/src/main/conclave/data/layouts.cljc), though, it looks like it'd be fairly straightforward to add them. The layouts are available on other map generators, but [Derek Peterson's generator](https://ti4-map-generator.derekpeterson.ca/) doesn't support PoK, while  [Keeganw's](https://keeganw.github.io/ti4/?settings=T54007129FFF) tends to produce fairly unbalanced notch maps - I often find that the players on the "horns" only have one "safe" planet next to their home system, while the other players have three solid, immediately useful systems to start colonising. I'm hoping that your balancing algorithm will do a better job!

**Comment by deadeyejoe** [comment]
Sorry for the late response, busy weekend! 

Cool you want to add those maps! Adding new layouts was one of the things I was aiming at when I wrote the app, so it should just be a matter of adding to `layouts.cljc`. I also wrote the balancing algorithm to be as layout-agnostic as possible, so hopefully it'll give you decent results - can't promise that obviously, but if you do notice problems/persistent biases please let me know.

I'm gonna write up a quick readme for it now. The instructions you mention for the codenames app are basically just gesturing at other people's documentation, so I reckon they could be tough to follow.

**Comment by deadeyejoe** [comment]
Added a [readme](https://github.com/deadeyejoe/deck/tree/master/projects/conclave#adding-map-layouts) just now,  hopefully it's clear, let me know what you think!
