### ISSUE TITLE
[Conclave] Generating a screenshot causes hyperlanes to be oriented in the wrong way

### ISSUE THREAD

**Issue by PietroCarrara** [deadeyejoe/deck#5]
## Steps to reproduce

1. Assemble a map using hyperlanes (for example, `87A1 90B3 65 88A2 89B0 66 19 21 45 31 46 64 22 73 44 34 49 24 27 50 72 40 59 85B2 62 76 41 37 43 35 48 63 83B2 74 36 79 0 42 30 0 0 0 0 68 0 0 47 71 0 39 61 0 0 0 0 67 0 0 78 28`)
2. Press 'Take a screenshot of the map'

## Expected Result

An image that looks like what I see on my screen:

![image](https://github.com/deadeyejoe/deck/assets/26305940/cef8585c-4f68-4e65-aa8b-aa2954af0aee)

## Actual Result

(Notice the hyperlanes)

![conclave-19](https://github.com/deadeyejoe/deck/assets/26305940/a520a7f5-62aa-4b02-9df5-1b2ddc18c524)

**Comment by deadeyejoe** [comment]
Thanks for the bug report! Not sure when I'll get the chance to look at it but I'll try and do it soon

**Comment by PietroCarrara** [comment]
I'll take a bet and say the screenshot code is applying rotations when the tile-rendering code is already applying them, but I can't wrap my head arround cljs :rofl:
